Sprint1/step1
BJuice1984/react-burger pull request #1
Opened 2023-01-20 05:43 UTC by BJuice1984

2023-01-20 08:11 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете хуки и PropTypes.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Не работает закрытие модалки по нажатию на подложку. 
- Не хватает типизации пропсов через `propTypes` для некоторых компонентов
- Не хватает компонента подложки `ModalOverlay`.
- Необходимо избавиться от дубликатов типизации ингредиента
- Необходимо конкретизировать типы данных у некоторых пропсов.

Более подробно описание проблемы смотрите комментарии в pull request.

Что понравилось:
- Сделали проверку успешности запросов.
- Проект соответствует макету
- Использовали деструктуризацию пропсов.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-01-20 08:11 UTC, andryxxa93 commented on src/components/BurgerConstructor/BurgerConstructor.js
> +        {mainIngridients.length &&
**Можно лучше**
Вы делаете одну и ту же проверку по многу раз. Можно сделать лаконичнее
```
{sauceIngridients.length && <React.Fragment>
< здесь все элементы >
< / React.Fragment>

```

2023-01-20 08:11 UTC, andryxxa93 commented on src/components/BurgerIngredients/BurgerIngredients.js
> +  bunIngridients: PropTypes.array.isRequired,
**Необходимо исправить**
Сейчас получается, что в пропсы могут прийти массивы любого содержания. Хотя это не так.

2023-01-20 08:11 UTC, andryxxa93 commented on src/components/BurgerIngredientsCard/BurgerIngredientsCard.js
> +  ingridient: PropTypes.shape({
**Надо исправить**

во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать

2023-01-20 08:11 UTC, andryxxa93 commented on src/components/ModalCard/ModalCard.js
> +export default function ModalCard() {
**Необходимо исправить**
Необходимо отображать не моковые данные, а данные того ингредиента на который нажал пользователь.

2023-01-23 09:03 UTC, BJuice1984 commented
Здравствуйте, Андрей! Исправил замечания. 
- Вынес ModalOverlay в отдельный компонент по заданию, только вот не понял смысл этого)) 
- Добавил проверку типов пропсов. 
- Скорректировал css. 
- Добавил хук useClose

2023-01-23 09:05 UTC, BJuice1984 commented on src/components/BurgerIngredientsCard/BurgerIngredientsCard.js
> +  ingridient: PropTypes.shape({
Спасибо за подсказу по структуре. Так и сделал

2023-01-23 09:05 UTC, BJuice1984 commented on src/components/BurgerIngredients/BurgerIngredients.js
> +  bunIngridients: PropTypes.array.isRequired,
Исправил

2023-01-23 09:06 UTC, BJuice1984 commented on src/components/App/App.tsx
> +        <Routes>
Пока оставил, чтобы <Link to=> не ругался

2023-01-23 09:06 UTC, BJuice1984 commented on src/components/BurgerConstructor/BurgerConstructor.js
> +        {mainIngridients.length &&
Отлично! Спасибо, так и сделал

2023-01-23 19:32 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!
В `pull-request` есть пару замечаний как **можно улучшить** код.

2023-01-23 19:32 UTC, andryxxa93 commented on src/components/Main/Main.js
> +        <BurgerIngredients
**Можно лучше**
`bunIngridients, sauceIngridients, mainIngridients` лучше инициализировать внутри `BurgerIngredients`. Просто передавайте в компонент все ингредиенты.

2023-01-23 19:32 UTC, andryxxa93 commented on src/utils/prop-types.js
> +export const burgerIngredientArrayType = arrayOf(
**Можно лучше**
`export const burgerIngredientArrayType = arrayOf(burgerIngredientType);`

2023-01-24 09:14 UTC, merged