Sprint 2/step 2
BJuice1984/react-burger pull request #2
Opened 2023-04-10 05:51 UTC by BJuice1984

- Redux Devtools подключено
- Store создан
   1. список всех полученных ингредиентов,
   2. список всех ингредиентов в текущем конструкторе бургера,
   3. объект текущего просматриваемого ингредиента,
   4. объект созданного заказа.
- Переключение по Tab реализовано
- Подсвечивание Tab при скролле реализовано
- Реализация перетаскивания ингредиентов выполнена
- Вложенная сортировка ингредиентов выполнена

2023-04-10 06:48 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Используете `React.memo`
- Хорошо организовано хранилище
- Редьюсеры чистые функции

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Теперь необходимо получать номер заказа с сервера. Для этого вам необходимо на этот ендпоинт - `https://norma.nomoreparties.space/api/orders` отправить массив с айдишниками ингредиентов из конструктора.
- Не стоит позволять юзеру делать заказ с пустым конструктором
- `BurgerConstructorCard ` не хватает `propTypes`
- `BurgerIngredientsCard ` не указан один пропс в `propTypes`. Пожалуйста проверьте во всём проекте остальные компоненты.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-10 06:48 UTC, andryxxa93 commented on src/components/App/App.tsx
> +          <Route path='/sign-in' element={<Login />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-04-10 06:48 UTC, andryxxa93 commented on src/components/BurgerConstructor/BurgerConstructor.js
> +  const userIngridients = useSelector(state => state.userIngridients);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-04-16 21:07 UTC, BJuice1984 commented
- Получение номера заказа с сервера.
- Disabled кнопки при пустом конструкторе.
- `BurgerConstructorCard` добавлен propTypes.
- `BurgerIngredientsCard` добавлен propTypes.
- Селекторы вынесены в отдельные функции.

2023-04-17 08:10 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

**Можно лучше**
Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

2023-04-18 14:26 UTC, BJuice1984 commented
Спасибо большое за ревью!

2023-04-18 14:27 UTC, merged