Sprint 4/step 1
BJuice1984/react-burger pull request #5
Opened 2023-05-27 23:35 UTC by BJuice1984

Добавлена типизация компонентов проекта

2023-05-28 06:54 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Использовали `any` и `ts-ignore` только в крайних случаях
- Хорошая типизация компонентов и функций

Необходимо исправить:
- файлы `mainApi`, `ingredientApi` и `constants` так же нужно типизировать

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-05-28 06:54 UTC, andryxxa93 commented on src/components/BurgerConstructorCard/BurgerConstructorCard.tsx
>  		  const hoverClientY = clientOffset.y - hoverBoundingRect.top;
**Можно лучше**
Тут можно просто добавить восклицательный знак `clientOffset!.y` и тогда мы сообщим typescript, что уверены, что `clientOffset` не равен `null`

2023-05-28 17:09 UTC, BJuice1984 commented on src/components/BurgerConstructorCard/BurgerConstructorCard.tsx
>  		  const hoverClientY = clientOffset.y - hoverBoundingRect.top;
Спасибо!

2023-05-28 17:09 UTC, BJuice1984 commented
Добавлена типизация в API компоненты проекта

2023-05-29 08:22 UTC, andryxxa93 approved these changes
Отлично типизировали запросы, особенно проверки - так держать!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-29 18:55 UTC, BJuice1984 commented
Спасибо за ревью!

2023-05-29 18:55 UTC, merged