Sprint 5/step 1
BJuice1984/react-burger pull request #6
Opened 2023-06-21 16:00 UTC by BJuice1984

1. Типизация стора.
2. Создание страниц "Лента заказов", "История заказов" + доработка роутинга под них.
3. Создание мидлвары сокет соединения.

2023-06-21 17:35 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализована страница ленты заказов;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/ut6YFs4TnxgwJA> - нужно поправить верстку, в соответствии с макетом.

- В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива - <https://disk.yandex.com/i/erwglnqFL2ItFw>;

- Не стоит в url хранить целый объект заказа. У вас ведь есть запросы, используйте их. А если какие-то параметры заказа изменились? у пользователя тогда будут старые данные. Ну и `http://localhost:3000/feed/64932ae98a4b62001c85f9ec?status=done&name=Space%20%D1%82%D1%80%D0%B0%D0%B4%D0%B8%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B3%D0%B0%D0%BB%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9%20%D0%BA%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D1%8B%D0%B9%20%D0%B1%D1%83%D1%80%D0%B3%D0%B5%D1%80&number=9549&ingr={%22ingredients%22:[%22643d69a5c3f7b9001cfa093c%22,%22643d69a5c3f7b9001cfa0943%22,%22643d69a5c3f7b9001cfa0944%22,%22643d69a5c3f7b9001cfa093c%22]}&updatedAt=2023-06-21T16:52:58.025Z&_id=64932ae98a4b62001c85f9ec&orderPrice=2605` слишком громоздко) не думаю что пользователю будет удобно смотреть на это. Нужно чтобы url был: `/feed/:id` и `/profile/orders/:id`, без всяких query параметров.

- При клику на заказ в профили, меняется url на `feed`, и еще `:id` = `undefined` - <https://disk.yandex.com/i/GHUX3blKLH7TPA>

- При перезагрузке страницы пользователь должен оставаться в системе, если он авторизовался ранне и у него валидный токе (**валидный считается и истёкший токен, в этом случае вы должны запросить новый токен, и ещё раз совершить запрос.**). А если токен не валидны - `Invalid Token` приходит от запроса, то вы удаляете всё что связано с токеном (все куки, LocalStorage и т.д.) и перенаправляете пользователя на страницу авторизации.

- Везде где `let cookie = getCookie('token');`, `let` - нужно поменять на `const`;

### **Сделает код лучше:**

- Лучше сделать отдельный запрос, который будет проверять истёк ли токен, или нет.
  Обрабатывать ошибки запросов и при возникновении ошибки jwt expired и вызывать обновление токена при ошибке

  Для этого используйте обертку над fetch, примерно такую

  ```js
  // например вот так
  export const requestWithRefresh = async (url, options) => {
    try {
      const res = await fetch(url, options);
      return await checkResponse(res);
    } catch (err) {
      if (err.message === 'jwt expired') {
        const refreshData = await refreshToken();
        if (!refreshData.success) {
          Promise.reject(refreshData);
        }
        localStorage.setItem('refreshToken', refreshData.refreshToken);
        setCookie('accessToken', refreshData.accessToken);
        options.headers.authorization = refreshData.accessToken;
        const res = await fetch(url, options);
        return await checkResponse(res);
      } else {
        return Promise.reject(err);
      }
    }
  };
  ```

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

### **После исправления всех замечаний, работа будет принята)**

2023-06-21 17:35 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  const userIngredients: UserIngredientsType = useSelector(getUserIngridients);
**Надо исправить:**

Тут нет необходимости дополнительно указывать тип селектору, вы ведь используете типизированный хук `useSelector`.

2023-06-21 17:35 UTC, ArslanMustafin commented on src/components/Orders/Orders.tsx
> +  let token = getCookie('token');
**Надо исправить:**

1. Тут нужно использовать `const`, а не `let`;
2. Лучше перенести переменную в `useEffect`, иначе каждый раз при смене переменной, у вас будет срабатывать `useEffect`.

2023-06-21 17:35 UTC, ArslanMustafin commented on src/components/Orders/Orders.tsx
> +  const isOrders: boolean = !!useMatch({ path: `${PROFILE}/${ORDERS}`})
**Надо исправить:**

не совсем понимаю зачем вам тут проверка на `url`. Точно ли она так необходима ?

2023-06-21 17:35 UTC, ArslanMustafin commented on src/services/reducers/orderHistory.ts
> +  }
**Можно лучше:**

тут лучше просто `null` поставить, а не писать начальные значения. Пользователь то их видит, и это не очень правильно.

2023-06-21 17:35 UTC, ArslanMustafin commented on src/utils/mainApi.tsx
> +export const logout = (token: string | null, cookie: string | null) => {
**Надо исправить:**

здесь и далее.

cookie или token - нужно получать в момент запроса, поэтому их лучше получать тут, а не где-то по среди компонента.

2023-06-23 16:58 UTC, BJuice1984 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  const userIngredients: UserIngredientsType = useSelector(getUserIngridients);
Исправил

2023-06-23 17:17 UTC, BJuice1984 commented on src/services/reducers/orderHistory.ts
> +  }
Исправил

2023-06-25 12:43 UTC, BJuice1984 commented on src/components/Orders/Orders.tsx
> +  const isOrders: boolean = !!useMatch({ path: `${PROFILE}/${ORDERS}`})
Убрал. Из компонента Feeds тоже

2023-06-25 16:30 UTC, BJuice1984 commented on src/utils/mainApi.tsx
> +export const logout = (token: string | null, cookie: string | null) => {
Перенёс запросы в mainApi

2023-06-25 17:24 UTC, BJuice1984 commented on src/components/Orders/Orders.tsx
> +  let token = getCookie('token');
Исправил

2023-07-01 06:45 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Практически все замечания были исправлены;

Рекомендую исправить замечания в коде))

2023-07-01 06:45 UTC, ArslanMustafin commented on src/services/actions/checkAuth.ts
> +let cookie = getCookie('token');
**Надо исправить:**

Получать токен лучше внутри функции

```js
export const checkAuth = () => {

  const cookie = getCookie('token');

// ...
}
```

2023-07-01 06:45 UTC, ArslanMustafin commented on src/utils/IngridientsApi.tsx
> +const cookie = getCookie('token');
**Надо исправить:**

Получать токен лучше внутри функции

```js
export const postIngridients = (ingridientsId: Array<string>) => {

  const cookie = getCookie('token');

// ...
}
```

2023-07-01 06:45 UTC, ArslanMustafin commented on src/utils/mainApi.tsx
> +const cookie = getCookie('token');
**Надо исправить:**

Получать токен лучше внутри функций. Показал примеры ранее в комментариях.

2023-07-03 15:13 UTC, BJuice1984 commented on src/services/actions/checkAuth.ts
> +let cookie = getCookie('token');
Исправил

2023-07-03 15:17 UTC, BJuice1984 commented on src/utils/IngridientsApi.tsx
> +const cookie = getCookie('token');
Исправил

2023-07-03 15:20 UTC, BJuice1984 commented on src/utils/mainApi.tsx
> +const cookie = getCookie('token');
Исправил

2023-07-03 15:20 UTC, BJuice1984 commented
Спасибо за ревью!

2023-07-03 15:20 UTC, merged